# Generated by Django 6.1.1 on 2026-09-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ESTOQUE', 'Estoque'), ('VENDEDOR', 'Vendedor'), ('CAIXA', 'Caixa'), ('COMPRAS', 'Compras')], default='VENDEDOR', max_length=20),
        ),
    ]
