# Generated by Django 6.1.1 on 2026-09-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome_empresa', max_length=255)),
                ('CNPJ', models.CharField(blank=True, db_column='cnpj', max_length=20, null=True)),
                ('telefone', models.CharField(db_column='telefone', max_length=20)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('categorias', models.CharField(blank=True, db_column='categorias', max_length=255, null=True)),
            ],
            options={
                'db_table': 'fornecedores',
            },
        ),
    ]
