# Generated by Django 6.1.1 on 2026-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='categorias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
